#!/bin/bash

#Install nodejs (adafruit installer)
if [ ! -e /usr/local/bin/node ];then
	/show/listecho "Install nodejs (adafruit)" $OK
	curl -sLS https://apt.adafruit.com/add | sudo bash
	apt-get update
	/system/install node
	nodeversion=$(node -v)
	/show/listecho "Node version $nodeversion" $OK
fi

/system/makedir /user/config/webcontrols
#Generate https certificate based on hostname in /user/config/webcontrols/
/do/webcontrols/https

#Generate default password
/do/webcontrols/password raspberry

#Copy default configuration
cp /do/webcontrols/conf/webcontrols.json /user/config/webcontrols

#Generate supervisord service

